// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Tue Dec 06 15:18:58 2022

ControlUnit ControlUnit_inst
(
	.Enter(Enter_sig) ,	// input  Enter_sig
	.CLR(CLR_sig) ,	// input  CLR_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.A_Load(A_Load_sig) ,	// output  A_Load_sig
	.B_Load(B_Load_sig) ,	// output  B_Load_sig
	.R_Load(R_Load_sig) ,	// output  R_Load_sig
	.OU_Load(OU_Load_sig) ,	// output  OU_Load_sig
	.RESET(RESET_sig) ,	// output  RESET_sig
	.IU_AU(IU_AU_sig) 	// output  IU_AU_sig
);

defparam ControlUnit_inst.s0 = 'b00;
defparam ControlUnit_inst.s1 = 'b01;
defparam ControlUnit_inst.s2 = 'b10;
defparam ControlUnit_inst.s3 = 'b11;
